### PR TITLE
Reduce size of XML

### PR DESCRIPTION
**Pull request by mbtools**
Strip tags containing descriptions (short texts) for TABL and FUGR

### CODE REVIEW

**Comment by larshp** [comment]
its difficult to say how much this gives, 3 times table loops with `DELETE lt_strings WHERE table_line` is added, it will save a bit of time transferring and a bit of time parsing

is 
`DELETE lt_strings WHERE table_line CP '<SHORT_TEXT>*</SHORT_TEXT>' OR table_line CP '<STEXT>*</STEXT>' OR table_line CP '<DDTEXT>*</DDTEXT>'.` allowed? it would give just one full table scan of `lt_strings`

**Comment by ed-holland** [comment]
Did you already remove the text of the message? That should reduce the bigger MSAG to a few kb (and not hundreds Kb).

**Comment by mbtools** [comment]
I combined the conditions. Saves a handful of microsec maybe. You would need a million executions to make a difference. 

Also added MSAG to the stripping which should reduce the load a bit more. 

Sidenote: If you have a while, do some measurements in SE38 -> Environment -> Performance examples. Most of it is 0 microsec for bad and good example.

**Comment by larshp** [comment]
yea, it always surprises me how fast computers are now-adays, but for this it also adds up, if there are 1000 objects with XML files of 1000 lines, its 1mio lines, times 3x or 1x loop

**Pull request merged**
