### PR TITLE
Cleanup & enabled sap original check

### PR DESCRIPTION
**Pull request by ed-holland**
Check enabled that other tests can be performed and SCI does not hang.
Issue #58

### CODE REVIEW

**Comment by larshp** [comment]
hmm

**Comment by ed-holland** [comment]
updated type detection.

**Comment by larshp** [comment]
I think we need some changes regarding the SAP objects, but we can take that later

**Comment by ed-holland** [comment]
> I think we need some changes regarding the SAP objects, but we can take that later

first trying to get the detection to work... refactoring can be done much easier when it works.

the only thing i think makes sense for non-existing objects is to tag them in a special way or just ignore them

**Pull request merged**
