### PR TITLE
default config api call proto

### PR DESCRIPTION
**Pull request by sbcgua**
#9 prototype, no intention to merge at the moment, just for debug, see `METHOD default_config`

2020-07-10_23h19_14

@g-back: what do you think ?

### CODE REVIEW

**Comment by g-back** [comment]
looks good, that functionality would be pretty useful (stringify, splice) - just wondering how we'll include the ajson stuff? just "copy paste" it here, make it a dependency?

**Comment by sbcgua** [comment]
@larshp what do you think on this subject ? I know you don't like dependencies :) But this is not abapgit from the other hand. I'm also OK to integrate that code into here, but this is has certain downsides: the code style differ (pretty printer to the rescue but maybe it will take more effort) and maintenance (I'll need ajson for other projects too so the maintenance will be more frequent). Also there are some activities for apack which may simplify dep handling.

**Comment by larshp** [comment]
I'm ok with adding dependencies to this project, just don't apack it

mention in readme for now, add dependency to abaplint.json

**Comment by larshp** [comment]
need the https://github.com/larshp/abapGit/issues/2236 solution for dependencies IMHO

**Comment by sbcgua** [comment]
> need the [larshp/abapGit#2236](https://github.com/larshp/abapGit/issues/2236) solution for dependencies IMHO

+1

OK, thanks. I'll have a look on it then

**Comment by larshp** [comment]
and this repo already have abapGit as a dependency

**Comment by g-back** [comment]
What's the state of ajson? Is the API stable (I see there are some open issues regarding renaming methods) or should we wait a bit until we migrate things to it?

**Comment by larshp** [comment]
migration is done https://github.com/abaplint/abaplint-sci-client/pull/87

**Comment by sbcgua** [comment]
> What's the state of ajson? Is the API stable (I see there are some open issues regarding renaming methods) or should we wait a bit until we migrate things to it? @g-back 

yeap, I consider changing `value*` to `get*` while it's not late (opinions are welcomed!) - https://github.com/sbcgua/ajson/issues/4, so maybe there will be one breaking change (but I'll syncronize it with a change in sci-client for sure)

**Comment by larshp** [comment]
no big problem if there are API changes, we'll just update here accordingly

**Comment by sbcgua** [comment]
Closing this in favor of #103

**Comment by sbcgua** [comment]
> no big problem if there are API changes, we'll just update here accordingly

yeap I will. Won't forget as I'm using sci-client/server too :) Cool stuff ! Just experimentally now, but must become mainstream :)

**Comment by larshp** [comment]
in the future I see a bot running, for every pull request(eg changes to ajson), look through all places(other repos) where it is used and check if the changes are compatible(via abaplint)

something that repo owners can set up optionally

**Comment by sbcgua** [comment]
... or running UTs with the transpiler ... ;)

**Pull request closed without merging**
