### PR TITLE
skip SI_ TABL objects if they are empty

### PR DESCRIPTION
**Pull request by larshp**
#219

@ed-holland can you help testing this change?

### CODE REVIEW

**Comment by ed-holland** [comment]
Sure... will find some time for it today.

**Comment by ed-holland** [comment]
PR branch code gives this error:
image

The LV_STRING which is retrieved from the file does not contain a DD02V tag (from si_fkkopr.tabl.xml).
`﻿<?xml version="1.0" encoding="utf-8"?>#<abapGit version="v1.0.0" serializer="LCL_OBJECT_TABL" serializer_version="v1.0.0"># <asx:abap version="1.0" xmlns:asx="http://www.sap.com/abapxml"/>#</abapGit>`

**Comment by larshp** [comment]
hmm, try setting a breakpoint

**Comment by ed-holland** [comment]
> hmm, try setting a breakpoint

That is how i got the LV_STRING. It did not replace anything so no fields where added.

**Comment by larshp** [comment]
okay, new plan

https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-us/abenddic_customizing_includes.htm

if `SI_`, includes are not found, abaplint will continue without errors,
https://github.com/abaplint/abaplint/blob/master/packages/core/src/objects/table.ts#L82

**Comment by larshp** [comment]
try again, logic updated

**Comment by ed-holland** [comment]
In SCI, the issue is now gone. Thx.

I've noticed two side effects:
1. AbapLint now shows the error (did not before)
image
2. Local Code shows difference with Remote Code
image

Is this caused by this PR or by the XML reduction also reducing namespace code?

**Comment by larshp** [comment]
1: `si_fkkopr` should not be part of deps anymore, did you update deps? Or perhaps there is a bug in it so it does not delete objects

2: I'm guessing its due to https://github.com/abaplint/abaplint-sci-client/pull/205

**Comment by ed-holland** [comment]
Updated AG/SCI to latest.
I've checked it using the deps_list utility and the includes are not generated anymore.
After the nightly rebuild of the Deps, they are also gone from the Dependency Repository. All is fine now.

**Comment by ed-holland** [comment]
Also the local differences are gone.

**Pull request merged**
