### PR TITLE
Add cache to abaplint client

### PR DESCRIPTION
**Pull request by mbtools**
Caches dependencies and serialized objects either in memory (for duration of session) or in cluster table. Currently cache options can be enabled in ZABAPLINT_LIST_DEPS, only. CI check ZCL_ABAPLINT_CHECK is already prepared (see RUN_BEGIN/END).

image

This needs proper testing regarding functionality as well as performance, of course. If cache is persisted, additional logic is required to deal with changes to SAP code (through notes, support packages, releases).

Will keep it in draft until testing is done.

### CODE REVIEW

**Comment by larshp** [comment]
run_begin added in https://github.com/abaplint/deps/commit/303ceedce7af1b6399c252ef184ec8727e43d8e7

also solves https://github.com/abaplint/abaplint-sci-client/issues/177

**Comment by larshp** [comment]
When running code inspector for a full package, it would typically run in parallel, ie. caching in session memory will not work for this scenario

I personally do not like storing data in cluster tables, suggest adding a new transparent table for the purpose, that way it will be removed when uninstalling the repo, plus its easy to see if it takes up a lot of space in the database. Take care of concurrency

Another option is shared memory objects, but I'd like not to battle it on 702, and it might also end up taking a lot of memory on each application server.

**Comment by ed-holland** [comment]
What about a complete other way.
Use a work-session on the linter side which initializes itself by already pulling the dependency repositories.
This should already reduce objects to be send a lot.
The parallel sci's would connect to the work-session and check their part.

**Comment by sbcgua** [comment]
I was also thinking about caching. Imho it should be on both sides. What about the following scenario:

1) client has some singleton **context** (how to manage in multithreading ?)
2) on the first touch, it requests new **session_id** from server, and stores it to the **context**
3) client find dependencies for object 1, it asks the **context** to filter those which were already sent to the server (non at this moment)
4) the client serializes deps and send all stuff, with the object 1 to the server, marking it with the **session_id**
5) server checks if the **session_id** exists, and in particular saves all the received objects (obj 1 and it's deps) into **session**
6) runs abalint, blah blah, return results ...
7) client starts with object 2 and find its dependencies. it asks the **context** to filter those which were already sent to the server (this time half of them are eliminated)
8) ...
9) end
10) ... cpu time passes ...
11) server **session_id** is timed out and droped (e.g. 5 min, or any other configurable value, or a refreshable (on each next request) timer, or external redis not to blow nodejs process up)

P.S. BTW, does the dependency classes serialized completely ? Or just definition ? It could speed up things

**Comment by larshp** [comment]
dependencies are reduced, so something like method definitions are removed, among other things

**Comment by larshp** [comment]
sessions are also difficult, especially if the client makes assumptions regarding the server.

having it RESTful makes it easy to scaleout

**Comment by sbcgua** [comment]
> dependencies are reduced, so something like method definitions are removed, among other things

I guess it makes sense to remove whole implementation. Well, anyway, just an idea

**Comment by larshp** [comment]
> > dependencies are reduced, so something like method definitions are removed, among other things
> 
> I guess it makes sense to remove whole implementation. Well, anyway, just an idea

it removes as much as possible, while still keeping abaplint happy, ie global classes must have an IMPLEMENTATION

**Comment by sbcgua** [comment]
> sessions are also difficult, especially if the client makes assumptions regarding the server.
> 
> having it RESTful makes it easy to scaleout

Mmm, yeah ... but network IO is relatively expensive ... I think it needs to be measured to claim something ... but intuitively I have a feeling that it would make difference.

scale out ... so external instance of redis accessible by several abaplint servers ... should work well ? Complex ? Maybe. I think we need some measurement criteria

**Comment by mbtools** [comment]
all good ideas. for me, the highest priority is doing things only once. that's currently a client-side problem since we dig for dependencies and serialize them for each object separately. this is addressed by the memory cache here... at least for single-tasking (and it already makes a big difference in my first tests). 

enhancing it for multi-tasking (for example, chang it to a shared memory class) would be prio 2.

anything beyond that should be based on runtime measurements or we will waste a lot of energy on things that don't matter.

**Comment by sbcgua** [comment]
> ... it already makes a big difference in my first tests

Bring in the benchmarks ! :)

**Comment by mbtools** [comment]
abapGit 1.99.1
abaplint-server 2.48.0
abaplint-client with #181 

Benchmark Setup: 
- Check variant: ZABAPLINT for $ABAPGIT with abaplint.json from Github, max depth = 12, continue into sap = off
- Object set: ZABAPGIT for $ABAPGIT + $ABAPGIT_*  (I have some other packages with $ABAPGIT...)
- Inspection: ZABAPGIT for ZABAPGIT variant and ZABAPGIT object set

Benchmark Execution:
- Start transaction SCI
- Run inspection, wait for completion, check runtime stats (should be ~390 objects)
- Exit transaction completely

Test Scenarios:
- Set caching options here:
```
ZCL_ABAPLINT_CHECK:
METHOD run_begin.
...
    lo_cache = zcl_abaplint_deps_cache=>get_instance( iv_memory = abap_...
                                                      iv_cluster = abap_... ).
...
```
- Run test, exit SCI, run test again

Test | First Run | Second Run
---- | ---- | ----
No caching (false, false) | 13:48 | 14:00
Memory cache (true, false) | 6:24 | 6:23
Cluster cache (true, true) | 6:25 | 5:07

(Size of cached data is 4 MB)

**Comment by larshp** [comment]
guess above is single-threaded? For getting SCI to run faster, its easy to run the inspection in parallel, and I assume/guess and recommend this to be the default for users when checking multiple objects

I expect/guess the memory cache improvement to be negative when running in parallel.

I'd also recommend changing to use normal transparent tables instead of cluster, I don't like installing this into systems potentially leaving data behind that will never be cleaned up(assuming nobody remembers to clean up at uninstall)

**Comment by sbcgua** [comment]
> I expect/guess the memory cache improvement to be negative when running in parallel.

why ?
BTW is there a good way to share data between threads in SAP, except tables? Could be a good option.

**Comment by larshp** [comment]
shared memory objects, https://github.com/abaplint/abaplint-sci-client/pull/181#issuecomment-696533623 but it can get quite complicated with locking, plus I'd like not to battle it with 702 as target version

**Comment by mbtools** [comment]
The cluster table was just a hack to persist the cache with little code. I will try with transp.table and select singles. Could be quite fast with single record buffering on the app server which would also work with multitasking.

**Comment by mbtools** [comment]
Btw the diff between memory and cluster is basically the time it takes to serialized the objects (approx 20%). And yes, the tests were single threaded.

**Comment by ed-holland** [comment]
will also try to run the tests (including caching) also with my mayor project. It currently takes about 45 min in SCI and less then 2 minutes with Linter-cli.

Due to the big difference in time, we might want to look at a different approach. 
Also there is still the issue of different results from both.

Case SCI of full repo:
AG knows which objects deviate from what is stored in the repo. It would be sufficient to serialize only the changed ones.
Process: Send Json, SCI-Server initializes (clone repo, clone deps), Send changed objects, Run Linter.

Case SCI of partial sources:
AG to serialize the selected objects + dependent objects of package tree.
Process: Send Json, SCI-Server initializes (clone deps), Send serialized objects, Run Linter.

The caching would still help to improve the serialization. The further processing would be then consistent with Linter-cli.

**Comment by ed-holland** [comment]
I'v ran the ZABAPLINT_LIST_DEPS (with serialize option) with our package tree which generates 36473 files in the background.

- without caching 548 seconds
- with disk caching 554 seconds
- with memory caching 565 seconds

I was surprised at first, but the Deps generation already removes duplicates before it serializes. As such, caching is not helping here.

**Comment by ed-holland** [comment]
I've used the tool ZABAPLINT_RUN_SCI to run the main Package with 307 objects in background. SCI-Server is 2.49.1

Without caching: 1947 seconds
With Disk caching: 880 seconds
With Memory caching: 841 seconds

Quite some improvement here i would say. Thx @mbtools

**Comment by mbtools** [comment]
Nice. Better than 50% improvement

Remember that disk caching will only show improvement on the second and subsequent runs (it saves the memory cache to disk at the end of the run). It currently only saves SAP-objects to disk (no Y,Z,or namespaces) since these objects remain stable (`ZCL_ABAPLINT_DEPS_CACHE->SAVE`). When I move this to transparent table, we could cache all code objects and check TRDIR-UDAT to see if the code is newer than cache.

**Comment by mbtools** [comment]
I changed over to 2 transparent tables for dependencies and serialized files. This should take care of multi-tasking. 

Memory and disk cache are "on" for SCI and ATC (see `run_begin`). DEPS_LIST has the options on the selection screen with default "off'.

As a side-effect, you can see roughly how much data each serialized object requires (`zabaplint_cache2-len`). 

Open issue: 
- Determine and save "last changed" date in cache for each object (udate field)
- Invalidate cache of newer objects

**Comment by larshp** [comment]
last changed: is difficult to determine, plus quite expensive to calculate. 

Instead I'd suggest to cache stuff for like 10 minutes, or longer if the development is in Z namespace and the dependencies are SAP namespace

**Comment by mbtools** [comment]
Added basic timestamp logic (see `check_timestamp`).

**Comment by ed-holland** [comment]
Tried to use the latest version for benchmarking second run, but i'm missing IF_ABAP_TIMESTAMP_UTIL. If it is not available in 740, then it surely is not available in 702. Is there an alternative?

**Comment by mbtools** [comment]
I changed to CL_ABAP_TSTMP which works in 702 as well

**Comment by sbcgua** [comment]
Hmmm ... (NW731)
image

**Comment by sbcgua** [comment]
Do I understand correctly that I need to adjust params in `ZCL_ABAPLINT_CHECK->RUN_BEGIN` to run in different modes ?

**Comment by sbcgua** [comment]
to the question of network transfers ... below are some request size in bytes

image

P.S. the log can be modified in `app.ts` in morgan construct params. E.g. `morgan(':method :url :status :res[content-length] - :response-time ms')` ([see also](http://expressjs.com/en/resources/middleware/morgan.html))

**Comment by sbcgua** [comment]
Maybe offtopic, but ... deps are slow ... I'd go for offline deps ... or even disabling them completely for my purposes ... with all coolness and respect to caching ... :(

**Comment by mbtools** [comment]
Yes, mod of RUN_BEGIN is necessary. My screen-painter is currently broken so I can't add the options to the SCI check variant config. Sorry.

**Comment by mbtools** [comment]
The network load is mostly caused by serializing standard SAP FUGR:

image

Which parts of FUGR does abaplint actually need?

**Comment by larshp** [comment]
For screen, painter, suggest merging, then I can add change the dynpro

For size and calls, suggest moving that to a new issue

**Comment by ed-holland** [comment]
> to the question of network transfers ... below are some request size in bytes
> 
> image
> 
> P.S. the log can be modified in `app.ts` in morgan construct params. E.g. `morgan(':method :url :status :req[content-length] - :response-time ms')` ([see also](http://expressjs.com/en/resources/middleware/morgan.html))

An option to provide more verbose logging on the SCI-Server side would be appreciated and help with optimizing the performance.

**Comment by ed-holland** [comment]
Redoing the test with ZABAPLINT_RUN_SCI to run the main Package with 307 objects in background. SCI-Server is 2.49.1

Without caching: 1947 seconds (old test result)
With Disk & Memory active: 880 seconds: First run 990s, Second run 321 secs !

In my case it is also the FUGR but also Tables with biggest size (ca 37000 entries in cache2).
image

**Comment by ed-holland** [comment]
I've also reran the ZABAPLINT_LIST_DEPS with both flags activated.
The first run took 73s and the 2nd run 67. Much faster also.

The ZABAPLINT_DEPENDENCIES normally takes around 900s to process.

Performance in AG running SCI also improved. From about 45m to 8m! :-)

**Comment by sbcgua** [comment]
> > P.S. the log can be modified in `app.ts` in morgan construct params. E.g. `morgan(':method :url :status :req[content-length] - :response-time ms')` ([see also](http://expressjs.com/en/resources/middleware/morgan.html))
> 
> An option to provide more verbose logging on the SCI-Server side would be appreciated and help with optimizing the performance.

will do, https://github.com/abaplint/abaplint-sci-server/issues/247

**Comment by larshp** [comment]
@mbtools can we merge this PR?

I'd still like to remove the memory option, and only do database, but it can be done later

**Comment by mbtools** [comment]
Good to go. We can remove the pure memory option and update the UI in next PR

**Pull request merged**
