### PR TITLE
Default config from SCI-Server

### PR DESCRIPTION
**Pull request by g-back**
- add addtional button `Update with Default`
- new method to fetch default config from backend/sci-server
- replace literal URIs with constants

### CODE REVIEW

**Comment by larshp** [comment]
the new button will get the default configuration? in that case suggest renaming to "update with default" or something?

**Comment by sbcgua** [comment]
works well

image

One doubt. On error error is displayed in editor (replacing the content by the way ...). Is it the intended behavior ?

2020-07-16_19h41_46

**Comment by g-back** [comment]
Good catch, I'll fix it tomorrow

**Comment by g-back** [comment]
Error message is now displayed as a message instead of overwriting the existing config.

**Pull request merged**
